### ISSUE TITLE
Error During InstallTortillaDriver

### ISSUE THREAD

**Issue by Finlaydag33k** [CrowdStrike/Tortilla#5]
as the title says, I can't install tortilla
![capture](https://cloud.githubusercontent.com/assets/6058378/6880480/d1aa2db2-d533-11e4-85c7-52ae3673ce44.PNG)

using windows 8.1 Pro

**Comment by geffner** [comment]
Did you follow the instructions in [README.txt](https://github.com/CrowdStrike/Tortilla/blob/master/README.txt) regarding configuring your system to support test-signed drivers?

**Comment by Finlaydag33k** [comment]
there was none... but I've re downloaded it, updating you soon!

**Comment by Finlaydag33k** [comment]
got it working now, seems that I wasnt running as admin .-. (my account didnt run as admin for some kind of strange reason)

**Comment by FR3egn37** [comment]
My laptop does not give me the option to disable the Security Boot Policy and disabling Security Boot stops my laptop from even starting, I don't want to reinstall my OS in none Security Boot mode is there any way to get that driver installed, or away around from using the driver?
